name: 2-Build & Publish Docker Image / SCA Agent

# This step will build and publish the Docker image to https://hub.docker.com/repository/docker/veracodedemolabs/petstore_api_python_github
# It then runs a SCA Agent scan against the repo and the container.
# It will run manually or automatically after 1-Checkout-Build-Artifact.yml completes.

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["1-Checkout-Build-Artifact"]
    types:
      - completed

jobs:
  Dockerize-Publish:
    runs-on: ubuntu-latest
    steps:

# Checkout code
    - uses: actions/checkout@v3

# Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

# Build and push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: roanlinde/petstore_api_python_github:latest

# Running Software Composition Analysis against the local repo and the container

    - name: SCA Agent Scan of Repo
      env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan
      
    - name: SCA Container Scan
      env: 
        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
      run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --image roanlinde/petstore_api_python_github:latest
